services:
  - type: worker
    name: escanor-bot
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: SESSION_ID
        sync: false
      - key: OWNER_NUMBER
        sync: false
      - key: OWNER_NAME
        value: Escanor
      - key: BOT_NAME
        value: "Escanor - Lion Sin of Pride"
      - key: PREF
        value: "."
